### ISSUE TITLE
compatibility issues with orchardcore

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/Library#208] opened 2022-08-26 07:08 UTC
![image](https://user-images.githubusercontent.com/13956765/186841537-888916da-1a4a-402d-8758-f73d2cfc2990.png)

Here is not the ability to internally block out duplicate discovery registrations

![image](https://user-images.githubusercontent.com/13956765/186842681-51cdcb88-1d7a-4e43-b57c-86eaba8e048b.png)

![image](https://user-images.githubusercontent.com/13956765/186842995-f8ea3eba-4742-4c77-a47c-301e2a95241c.png)

but i just want the event excute once

**Comment by dj-nitehawk** [comment] 2022-08-26 11:23
you're not supposed to publish the request dto as an event model. you need use a seperate event dto for the purpose of communicating state to the subscribers. i.e. `PublishAsync()` should not use request dtos. you can create event dtos by inheriting from request dtos but don't use request dtos directly.

if that doesn't solve it, pls send a small repro project i can debug. and pls don't post pictures of code. if that was text, i could easily copy/paste and run it myself to check. the amount of time i can spend on helping is extremely limited. having to re-type your code makes my life harder. hope you understand :-)

**Comment by vipwan** [comment] 2022-08-26 11:45
Sorry for spending so much of your precious time ,
I tried it according to your solution and still didn't fix the problem, My test code is very simple ,just like the get-started code, The only extra part is invoke `services.AddFastEndpoints();` twice or more .

**Comment by dj-nitehawk** [comment] 2022-08-26 11:47
no worries. but why do you call `services.AddFastEndpoints();` multiple times?
that's not how it's supposed to be used. pls explain why you're calling it multiple times...

**Comment by dj-nitehawk** [comment] 2022-08-26 11:50
ah i think i understand your need. you want to filter out multiple things right? fix is simple, just combine the conditions with `&&` like so:

```cs
options.Filter = t => (SomeCondition) && (AnotherCondition)
```

**Comment by vipwan** [comment] 2022-08-26 11:50
Because I use OrchardCore multi-tenant system as a secondary development
Why I've signed up multiple times I haven't gone into it yet

**Comment by dj-nitehawk** [comment] 2022-08-26 11:52
i'm not familiar with orchardcore. but you're definitely not supposed to call `services.AddFastEndpoints();` multiple times in a single application context. pls send a small repro project or upload to github so i can get a better understanding.

**Comment by vipwan** [comment] 2022-08-26 11:56
> 
The same code I use MediatR as an EventBus, there will be no problem even if MediatR is registered multiple times

**Comment by dj-nitehawk** [comment] 2022-08-26 11:59
fastendpoints is a completely different beast and much faster than mediatr since we use a different technique for message publication. what exactly is the reason you need to call `AddFastEndpoints()` multiple times? to add to the filter right? then just simply combine the conditions into 1 filter predicate. problem solved. if that's not the reason. show me project code.

**Comment by vipwan** [comment] 2022-08-26 12:10
So I now have to use MediatR to replace fe's event bus, because MediatR does solve my problem very well,  

Wait a minute for me to release a test case to github

**Comment by vipwan** [comment] 2022-08-26 12:37
I created a test case ,   [TestAppWithFE](https://github.com/vipwan/MicroSvcTest/tree/master/TestAppWithFE)

**Comment by dj-nitehawk** [comment] 2022-08-26 14:14
going through the code now. can you help me understand why orchardcore create multiple instances of the app without any memory isolation? it looks like they're all running in the same application domain. can you point in to the documentation where they describe this (very bad) behavior?

**Comment by dj-nitehawk** [comment] 2022-08-26 14:42
so yeah... from the vague info i could find about orchard. they're running multiple instances of the app inside the same app domain. which is something FE can't handle right now. since this is not something we're interested in doing anyway, because it has no use outside of third-party tools like orchardcore, i'll close this issue.

**Comment by vipwan** [comment] 2022-08-26 16:17
Sorry, I didn't get timely feedback because of the time difference between each other . 

Actually, if I could modify the source code of FE, I could solve this problem 
![image](https://user-images.githubusercontent.com/13956765/186948385-743f1533-fb1d-4b67-964f-38daac2193fc.png)
![image](https://user-images.githubusercontent.com/13956765/186948480-9babd0d8-15fc-41e2-90b0-11c65d869a9e.png)

However, this comes with a small performance overhead  :)

**Comment by dj-nitehawk** [comment] 2022-08-26 16:29
is orchard using an instance per tenant? is that why it's spinning up 5 instances under the same app domain?
this is just crazy behavior. even the service collection is shared among all the instances right?
can't use any static variable anywhere in your app right?

so... even if we only allow it to subscribe just once, since the underlying system is static, state is not purely isolated inbetween the multiple instance and it could lead to weird behavior. is there no way to configure orchard to not run multiple instance under 1 appdomain?

**Comment by vipwan** [comment] 2022-08-26 16:34
Because of multi-tenancy, there will be different shells, but there is only one type globally, just the objects are isolated by each other , So I don't think that's any impact

**Comment by vipwan** [comment] 2022-08-26 16:36
I look at the code for FE (consumer definition here) and this part is obtained through reflection rather than through containers resolve

**Comment by vipwan** [comment] 2022-08-26 16:41
So why didn't I start by saying it was a Problem with OrchardCore, but instead mentioned the case of multiple registrations, because registering multiple times in a container overwrites the previous registration ,but doesn't affect the DI of the system

**Comment by dj-nitehawk** [comment] 2022-08-26 16:53
give me some time to think about this and come up with a better solution. it's time for me to call it a day. will get back to you on this tomorrow.

**Comment by vipwan** [comment] 2022-08-26 16:58
> give me some time to think about this and come up with a better solution. it's time for me to call it a day. will get back to you on this tomorrow.

Haha I'm a night owl and if there's any news to communicate with each other, I'd love to have FE more robust and recommend it to friends around me

**Comment by dj-nitehawk** [comment] 2022-08-27 07:01
i'm investigating this now.
do you know if orchardcore shares the ioc container (IServiceProvider) amongst all the instances?
or does each instance have their own DI container instance?

reason i'm asking is because fastendpoints stores a reference to the `IServiceProvider` in a static var and uses it in multiple places like validators, validators, evenhandlers etc.

**Comment by vipwan** [comment] 2022-08-27 07:28
https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore/OrchardCore/Shell/Builders

![image](https://user-images.githubusercontent.com/13956765/187019892-4e9b1f13-ca56-46d5-8f84-e76a62e588aa.png)
![image](https://user-images.githubusercontent.com/13956765/187019947-83303b16-ea14-4ace-b6df-8c2cbac63fdd.png)

The relevant information should be found here : 

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore/Shell/Builders/ShellContainerFactory.cs

**Comment by vipwan** [comment] 2022-08-27 07:37
If the global store some data statically, it will inevitably cause interference to different scope services, but the storage of reference should not be

**Comment by vipwan** [comment] 2022-08-27 07:48
From the few lines of code I modified yesterday, your processing logic doesn't seem to consider the scope of the scope, but directly uses Actor.CreateInstance(t)?. Subscribe(); So even if t is discovered multiple times you may think it's reasonable

**Comment by dj-nitehawk** [comment] 2022-08-27 17:00
can you try `v5.1.0-beta4`?
i reworked the event notification system.
it should now prevent duplicate registration.

**Comment by vipwan** [comment] 2022-08-27 17:26
> can you try `v5.1.0-beta4`? i reworked the event notification system. it should now prevent duplicate registration.

![image](https://user-images.githubusercontent.com/13956765/187041266-cb716a0d-0fb3-420f-bcbe-31d11c5eab44.png)

Nothing has changed

**Comment by dj-nitehawk** [comment] 2022-08-27 18:04
I don't get it then. 
cause now the handlers are prevented from being duplicated due to the hashset here: https://github.com/FastEndpoints/Library/blob/ec1558323e5ee6ee326417d2c6f4ac7045f5b9d1/Src/Library/Events/Event.cs#L10

**Comment by vipwan** [comment] 2022-08-27 18:10
![image](https://user-images.githubusercontent.com/13956765/187042791-ed7e0711-76bd-4bb7-9dc2-3f952e0c4b0d.png)

**Comment by vipwan** [comment] 2022-08-27 18:15
![image](https://user-images.githubusercontent.com/13956765/187042920-d23456aa-c93f-43fe-b3f0-2e63f5d3df45.png)

distinct  here, it can be solved

**Comment by dj-nitehawk** [comment] 2022-08-27 18:16
this is how i'm testing it and i'm seeing the correct behavior. don't know how to deal with the weird shit orchard is doing 😁
```cs
Task.Run(() =>
{
    var builder = WebApplication.CreateBuilder();
    builder.Services.AddFastEndpoints();
    builder.Services.AddSwaggerDoc();

    var app = builder.Build();
    app.UseAuthorization();
    app.UseFastEndpoints();
    app.UseOpenApi();
    app.UseSwaggerUi3(s => s.ConfigureDefaults());
    app.Run("http://localhost:88");
});

Task.Run(() =>
{
    var builder = WebApplication.CreateBuilder();
    builder.Services.AddFastEndpoints();
    builder.Services.AddSwaggerDoc();

    var app = builder.Build();
    app.UseAuthorization();
    app.UseFastEndpoints();
    app.UseOpenApi();
    app.UseSwaggerUi3(s => s.ConfigureDefaults());
    app.Run("http://localhost:89");
});

Console.ReadLine();

public class TestEvent
{
    public int Message { get; set; }
}

public class TestEventHandler : FastEventHandler<TestEvent>
{
    public override Task HandleAsync(TestEvent eventModel, CancellationToken ct)
    {
        var logger = ResolveSingleton<ILogger<TestEvent>>();
        logger.LogWarning("message: {@msg}", eventModel.Message);
        return Task.CompletedTask;
    }
}

public class Endpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test/{number}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await PublishAsync(new TestEvent { Message = Route<int>("number") });
    }
}
```

**Comment by dj-nitehawk** [comment] 2022-08-27 18:17
ok gimme some time... i'll look in to it.

**Comment by vipwan** [comment] 2022-08-27 18:19
I didn't use the OrchardCore test, just the base code for the Get Started code  

`builder.Services.AddFastEndpoints();// * N`

**Comment by dj-nitehawk** [comment] 2022-08-27 18:40
try `v5.1.0-beta4`
now the hashset should function properly.
it was checking equality between instances. needed equality between types.
i'm off to bed.
keep me posted. 
ciao!

**Comment by vipwan** [comment] 2022-08-27 18:50
Fantastic, finally found the problem !!!

**Comment by vipwan** [comment] 2022-08-28 16:18
@dj-nitehawk   

beta5->beta6 EventHandler  does not work , 

There should be some problems when upgrading the injection service  :(

**Comment by dj-nitehawk** [comment] 2022-08-29 11:37
i need a way to debug this. can you pls update the following program to use orchardcore and replicate the problem pls?
```cs
using FastEndpoints;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.Run();

public class Endpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendOkAsync();
    }
}
```

**Comment by vipwan** [comment] 2022-08-29 12:41
How should I assist with the test now ?

**Comment by vipwan** [comment] 2022-08-29 12:44
> 

Okay I'll wait for the new version to be released

**Comment by dj-nitehawk** [comment] 2022-08-29 12:52
`v5.1.0-beta7` is out. give it a shot.
thanks for reporting.

**Comment by vipwan** [comment] 2022-08-29 12:58
> `v5.1.0-beta7` is out. give it a shot. thanks for reporting.

It worked

**Closed** 2022-08-29 12:59 UTC
Labels: enhancement, implemented

**Comment by sfmskywalker** [comment] 2023-04-01 21:19
@vipwan I am working on an Orchard Core module that also leverages FastEndpoints. I was wondering, are you calling `AddFastEndpoints` from a module's Startup class, or from Program.cs?

Reason I'm asking is because when I call `app.UseFastEndpoints` from within a module's Startup's `Configure` method, I get the exception that no `IServiceResolver` was found.

Perhaps, if possible, could you share a sample of your module that I can try out?

**Comment by sfmskywalker** [comment] 2023-04-01 21:24
Here's a screenshot for a little bit of added context:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/938393/229314449-a9b6fa98-64fb-4a3c-8d58-48d25f7945e1.png">

**Comment by sfmskywalker** [comment] 2023-04-01 21:29
Wow, sorry - that exception is something else than what I saw earlier - obviously that has nothing to do with FastEndpoints. Please ignore this - I'll dig into this first.

**Comment by sfmskywalker** [comment] 2023-04-01 21:54
I wasn't able to reproduce the issue anymore, so please disregard all of my earlier comments.
I love FastEndpoints and I'm glad to see it works well with Orchard Core!
