### ISSUE TITLE
Swagger - Schema becoming "invalid" overnight

### ISSUE THREAD

**Issue by Conway6288** [FastEndpoints/Library#173] opened 2022-07-28 15:04 UTC
Quite lost on this one and I can't find anything else similar in the git issues.

My api is working fine with swagger etc but after leaving it running overnight attempting to go back to the swagger page the next day it produces a swagger.json error caused by a NullReferenceException with the below call stack. Simply restarting the service it works correctly. Any advice is appreciated!

Exception: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FastEndpoints.Swagger.ValidationSchemaProcessor.Process(SchemaProcessorContext context)
   at NJsonSchema.Generation.JsonSchemaGenerator.ApplySchemaProcessors(JsonSchema schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NSwag.Generation.OpenApiSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NSwag.Generation.AspNetCore.Processors.OperationResponseProcessor.Process(OperationProcessorContext operationProcessorContext)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by dj-nitehawk** [comment] 2022-07-28 15:08
@wjax did we come across something like this on discord?
any ideas what could be going on?

**Comment by dj-nitehawk** [comment] 2022-07-28 15:16
@Conway6288 in the meantime, could you do please re-deploy your app with PDB file so we can see line numbers in the stack trace? it could help in narrowing down the issue since this is not reliably reproducible locally for us to debug.

**Comment by wjax** [comment] 2022-07-28 15:44
I'll set up a test to try to catch it

**Comment by Conway6288** [comment] 2022-08-01 07:22
It happens in release with the server running overnight without load. As soon as you try and access the /swagger endpoint you are shown a /swagger/v1/swagger.json error. Going to the page details the stack trace from my original post.

Over the weekend I have had it setup to restart the service at 2am, seems to have fixed it for the moment but I will disable that to get you some extra information. I have republished our api with the pdb files included.

Will send the stack through tomorrow morning.

**Comment by Conway6288** [comment] 2022-08-02 07:59
Have run the /swagger endpoint this morning and again it returns a "Failed to load API Definition. Fetch error - response status is 500 /swagger/v1/swagger.json"

The stack trace is the same, I cannot see any line numbers:

System.NullReferenceException: Object reference not set to an instance of an object.
   at FastEndpoints.Swagger.ValidationSchemaProcessor.Process(SchemaProcessorContext context)
   at NJsonSchema.Generation.JsonSchemaGenerator.ApplySchemaProcessors(JsonSchema schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NSwag.Generation.OpenApiSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NSwag.Generation.AspNetCore.Processors.OperationResponseProcessor.Process(OperationProcessorContext operationProcessorContext)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by dj-nitehawk** [comment] 2022-08-02 08:07
interesting indeed...
line numbers are missing most probably because the exception is thrown from inside nswag (if i'm not mistaken).
@wjax what do you think?
i think we will have to do that logging thing with the try/catch we discussed on discord.

**Comment by wjax** [comment] 2022-08-02 08:25
I'll create the pull ASAP.
I have done the same (keep pc running all night etc etc) and have not seen it failing

**Comment by dj-nitehawk** [comment] 2022-08-02 15:22
@Conway6288 are you by any chance running your app on IIS like this one: https://github.com/dj-nitehawk/FastEndpoints/issues/154#issuecomment-1202779482

**Comment by Conway6288** [comment] 2022-08-02 15:25
Yes, it is running in IIS. 

Recycling the app pool at 2am meant that when I tried to call swagger at 9am it works fine and continues to work throughout the day. Strange that without that enforced recycle it would cause an issue.

**Comment by dj-nitehawk** [comment] 2022-08-02 15:28
aha... so this is IIS related...
if i remember IIS correctly, there's a setting to SUSPEND the app instead of TERMINATE due to inactivity.
could you set your app to not recycle (or set a very long recycle period) and set the inactivity action to SUSPEND.
let's see if that makes a difference.

**Comment by Conway6288** [comment] 2022-08-02 15:48
Will see what I can do, but in scenarios where the app should be terminated that would obviously not be feasible.

**Comment by dj-nitehawk** [comment] 2022-08-02 15:51
well, the thing is, if an app is terminated, it should be properly started back up from scratch in which case shouldn't cause this issue.

**Comment by Conway6288** [comment] 2022-08-02 15:52
Agreed and recycling the app pool (Which terminates not suspends) fixes the issue. Will double check what we have setup.

**Comment by OFark** [comment] 2022-08-03 17:03
Our IIS was set to Terminate after 20 minutes, I've just set it to suspend instead. See what happens.

**Comment by dj-nitehawk** [comment] 2022-08-04 02:13
@Conway6288 @OFark 
pls re-deploy with `v4.5.0-beta1` and send back the log entries.
thanks!

**Comment by Conway6288** [comment] 2022-08-04 08:36
Done! Will send through logs tomorrow.

**Comment by devjuanca** [comment] 2022-08-04 11:18
Hello, I have a similar problem. I have an api deployed in azure that uses Fast Endpoints and after some time passes without activity,  it throws a 500 error "Failed to load api definition" in swagger. The service is restarted in azure and the problem is solved. Any idea what could happen? Thanks!

**Comment by wjax** [comment] 2022-08-04 11:23
I may be related, yes.

NSwag generates swagger.json at runtime and keep it in memory.
Maybe it could help to generate swagger.json at build time and persist it
to storage and serve it from there. What do you think?

Like explained here:
https://khalidabuhakmeh.com/generate-aspnet-core-openapi-spec-at-build-time?utm_source=pocket_mylist

**Comment by dj-nitehawk** [comment] 2022-08-04 17:50
@wjax yeah let's look in to that...

**Comment by dj-nitehawk** [comment] 2022-08-09 06:05
@wjax i've made some changes so that the validator types are cached internally by the validation processor.
hopefully `4.5.0-beta6` solves this...
everyone pls try that build and report back.
thanks!

**Comment by wjax** [comment] 2022-08-09 06:13
> @wjax i've made some changes so that the validator types are cached internally by the validation processor.
> 
> hopefully `4.5.0-beta6` solves this...
> 
> everyone pls try that build and report back.
> 
> thanks!

Ok. However I am not at all certain that the null reference come from the validation types. If it comes from there, the stack trace would come from an inner method. However it comes from the entry method "Process"

Anyway, has there been any reports of exception after the "hardening"?  Just curiosity

**Comment by dj-nitehawk** [comment] 2022-08-09 07:52
@wjax haven't received any reports yet...
lets wait and see...

**Comment by Conway6288** [comment] 2022-08-09 08:15
Since I deployed with v4.5.0-beta1 it seems to be ok for me at least, this morning there are no issues and the swagger ui is working correctly.

**Comment by OFark** [comment] 2022-08-09 14:05
I too failed to see it fall over after 4.5.0-beta1. Though I've been on annual leave this week, I'll check in with the team on Monday.

**Comment by dj-nitehawk** [comment] 2022-08-09 14:07
@Conway6288 @OFark pls upgrade to `4.5.0-beta6` when you can. also check the logs to see if there's any failures there and let us know.

**Comment by dj-nitehawk** [comment] 2022-08-13 09:45
so i guess this problem is now solved with the latest betas?
i'll assume it is and close this issue for now.
feel free to re-open in case it pops up again...

**Closed by dj-nitehawk** 2022-08-13 09:45 UTC
Labels: bug, pending investigation
